- name: 10€ Amazon-Gutschein
  icon: amazon_10

- name: 50€ Amazon-Gutschein
  icon: amazon_50

- name: Autogrammkarte
  icon: autograph

- name: Treffen
  icon: meet_and_greet
  hue: 320
  saturation: 1000
  brightness: 50

- name: Merchandise
  icon: merch

- name: Rap-Part
  icon: rap_part

- name: Steam-Spiel
  icon: steam

- name: 100 PP
  icon: pp_100
  points: 100
  hue: 320

- name: 200 PP
  icon: pp_200
  points: 200
  hue: 320

- name: 500 PP
  icon: pp_500
  points: 500
  hue: 320

- name: 1000 PP
  icon: pp_1000
  points: 1000
  hue: 335

- name: 5000 PP
  icon: pp_5000
  points: 5000
  hue: 335

- name: 10000 PP
  icon: pp_10000
  points: 10000
  hue: 350

- name: 15000 PP
  icon: pp_15000
  points: 15000
  hue: 350
