- name: 10€ Amazon-Gutschein
  weight: 30
  icon: amazon_10
  brightness: 50
  hue: 1
  log_channel: giolette_specials

- name: 50€ Amazon-Gutschein
  weight: 10
  icon: amazon_50
  brightness: 50
  hue: 1
  log_channel: giolette_specials

- name: Autogrammkarte
  weight: 100
  icon: autograph
  hue: 50
  log_channel: giolette_specials

- name: Treffen
  weight: 3
  icon: meet_and_greet
  hue: 320
  saturation: 1000
  brightness: 50
  log_channel: giolette_specials

- name: Merchandise
  weight: 20
  icon: merch
  hue: 220
  log_channel: giolette_specials

- name: Rap-Part
  weight: 20
  icon: rap_part
  brightness: 40
  saturation: 200
  hue: 1
  log_channel: giolette_specials

- name: Steam-Spiel
  weight: 10
  hue: 190
  brightness: 45
  icon: steam
  log_channel: giolette_specials

- name: 100 PP
  weight: 1000
  icon: pp_100
  points: 100
  hue: 320
  log_channel: giolette_pp

- name: 200 PP
  weight: 900
  icon: pp_200
  points: 200
  hue: 320
  log_channel: giolette_pp

- name: 500 PP
  weight: 800
  icon: pp_500
  points: 500
  hue: 320
  log_channel: giolette_pp

- name: 1000 PP
  weight: 500
  icon: pp_1000
  points: 1000
  hue: 335
  brightness: 96
  log_channel: giolette_pp

- name: 5000 PP
  weight: 150
  icon: pp_5000
  points: 5000
  hue: 335
  brightness: 96
  log_channel: giolette_pp

- name: 10000 PP
  weight: 30
  icon: pp_10000
  points: 10000
  hue: 350
  log_channel: giolette_pp

- name: 15000 PP
  weight: 10
  icon: pp_15000
  points: 15000
  hue: 350
  log_channel: giolette_pp
